# Generated by Django 3.2.16 on 2023-04-04 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_follow_prevent_self_follow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='prevent_self_follow',
        ),
    ]
